name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint:fix

      - uses: autofix-ci/action@v1